### ISSUE TITLE
Updater not working ?

### ISSUE THREAD

**Issue by swinowz** [rLhRw4fjX/FrostBorn#1]
I don't understand how to setup basically, updater is giving me a file upload error, and what do you mean by "resize button" on the tutorial, also if you could make a video tutorial that would be great, thanks !

**Comment by rLhRw4fjX** [comment]
To compile the source code, you need kibor https://kibor-bot.com/ (as well as the full version at a cost of $5-9 for half a year of work). Updates do not work because the update server is disabled. "resize button" automatically changes the emulator window to the desired resolution in order to expose the correct areas for random clicks, image search, etc. Since the program works on the basis of the screen image analysis functions.

Also: The project is abandoned, there are a lot of crutches in this code due to the peculiarity of the development environment, and it is not completely finished. Perhaps the only thing that can be taken from here is logic, but there are no even normal comments in the code)
![4](https://user-images.githubusercontent.com/82238236/148603020-1c6602f8-1ad7-4a50-93a0-3a4ab42272c8.PNG)
